// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLDC.Models;

#nullable disable

namespace QLDC.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLDC.Models.DeCuong", b =>
                {
                    b.Property<int>("MaDeCuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDeCuong"));

                    b.Property<int>("MonHocMaMon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayPheDuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDeCuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<int>("VanPhongKhoaMaNhanVien")
                        .HasColumnType("int");

                    b.HasKey("MaDeCuong");

                    b.HasIndex("MonHocMaMon");

                    b.HasIndex("VanPhongKhoaMaNhanVien");

                    b.ToTable("DeCuong", (string)null);
                });

            modelBuilder.Entity("QLDC.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<int>("SoDienThoai")
                        .HasColumnType("int");

                    b.Property<string>("TenGiangVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGiangVien");

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("QLDC.Models.GiangVien_MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiangVienMaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("KyHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.Property<int>("MonHocMaMon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienMaGiangVien");

                    b.HasIndex("MonHocMaMon");

                    b.ToTable("GiangVien_MonHoc", (string)null);
                });

            modelBuilder.Entity("QLDC.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<string>("HinhThucThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMon");

                    b.ToTable("MonHoc", (string)null);
                });

            modelBuilder.Entity("QLDC.Models.VanPhongKhoa", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoDienThoai")
                        .HasColumnType("int");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("VanPhongKhoa", (string)null);
                });

            modelBuilder.Entity("QLDC.Models.DeCuong", b =>
                {
                    b.HasOne("QLDC.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocMaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDC.Models.VanPhongKhoa", "VanPhongKhoa")
                        .WithMany()
                        .HasForeignKey("VanPhongKhoaMaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("VanPhongKhoa");
                });

            modelBuilder.Entity("QLDC.Models.GiangVien_MonHoc", b =>
                {
                    b.HasOne("QLDC.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienMaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDC.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocMaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
